CUDA_VISIBLE_DEVICES=0 accelerate launch train_svd_my.py \
    --pretrained_model_name_or_path /data/lyq/data/stable-video-diffusion-img2vid \
    --base_folder /data/lyq/datasets/DAVIS-2019-test-dev-480p/JPEGImages/480p \
    --num_frames 16 \
    --output_dir ./output/2019-test-dev/baseline-avg_pred_noise \
    --per_gpu_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --num_train_epochs 100 \
    --max_train_steps 10000 \
    --width 512 \
    --height 320 \
    --checkpointing_steps 10000 \
    --checkpoints_total_limit 1 \
    --learning_rate 1e-4 \
    --lr_warmup_steps 0 \
    --seed 42 \
    --mixed_precision "fp16" \
    --validation_steps 1000